name: Build & Push

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build production image
        run: |
          docker build \
            --file Dockerfile.prod \
            --cache-from 192.168.1.192:5000/stevefuchs-fr:latest \
            --tag 192.168.1.192:5000/stevefuchs-fr:latest \
            .

      - name: Push to registry
        run: docker push 192.168.1.192:5000/stevefuchs-fr:latest
